require: rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "config/initializers/simple_form_bootstrap.rb"
    - "db/schema.rb"

Layout/LineLength:
  Max: 90
  IgnoredPatterns:
    - '\A(\s)*#'

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/*.rb"    
    - "config/routes.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"