dist: xenial
cache:
  bundler: true
language: ruby
install:
  - travis_retry nvm install 13.7.0
  - bundle
  - yarn
before_script:
  - cp config/database.yml.travis config/database.yml
  - rake db:create
  - rake db:migrate RAILS_ENV=test
script:
  - xvfb-run -a --server-args="-screen 0 1024x768x24" bundle exec rake
  - bundle exec rubocop --require rubocop-rails
services:
  - postgresql
  - xvfb
addons:
  firefox: latest
