dist: xenial
cache:
  bundler: true
language: ruby
install:
  - bundle
before_script:
  - cp config/database.yml.travis config/database.yml
  - rake db:setup
  - bundle exec rails webpacker:compile
script:
  - bundle exec rake
  - bundle exec rubocop --require rubocop-rails
services:
  - postgresql