dist: xenial
cache:
  bundler: true
  yarn: true
language: ruby
env:
  global:
    - RAILS_ENV=test
    - MOZ_HEADLESS=1
install:
  - travis_retry nvm install 13.5.0
  - bundle
  - yarn
before_script:
  - cp config/database.yml.travis config/database.yml
  - rake db:setup
  - bundle exec rails webpacker:compile
script:
  - xvfb-run -a --server-args="-screen 0 1024x768x24" bundle exec rake
  - bundle exec rubocop --require rubocop-rails
services:
  - postgresql
  - xvfb
addons:
  firefox: latest
