dist: xenial
cache: bundler
language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - rake db:setup
script:
  - bundle exec rake
  - bundle exec rubocop --require rubocop-rails
services:
  - postgresql