dist: xenial
cache: bundler
language: ruby
script:
  - bundle exec rake
  - bundle exec rubocop --require rubocop-rails
services:
  - postgresql
before_script:
  - psql -c 'create database paw_patrol_test;' -U postgres